version: '3.1'
services:
  db:
    image: postgres
    ports:
    - ${POSTGRES_PORT:-5432}:5432
    build: {
      context: /db,
      dockerfile: dockerfile
    }
    networks:
      - net
    environment:
      - POSTGRES_DB=links
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db 
  server:
    image: server
    ports:
      - 3000:3000
    build: {
      context: /server,
      dockerfile: dockerfile
    }
    networks:
      - net
    depends_on:
      - db
    environment:
      - dbName=links
      - dbUser=postgres
      - dbPass=postgres
      - dbPort=5432
      - dbHost=db
    container_name: server
networks:
  net:
    driver: bridge