version: '3.1'
services:
  db:
    image: postgres
    ports:
    - 8000:8000
    build: {
      context: /db,
      dockerfile: dockerfile
    }
    networks:
      - net
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    container_name: db 
  server:
    image: server
    ports:
    - ${POSTGRES_PORT:-5432}:5432
    build: {
      context: /server,
      dockerfile: dockerfile
    }
    networks:
      - net
    depends_on:
      - db
    environment:
      - dbName=db
      - dbUser=user
      - dbPass=123
      - dbPort=5432
    container_name: server
networks:
  net:
    driver: bridge