version: '3.9'
services:
  db:
    image: postgres
    ports:
    - ${POSTGRES_PORT:-5432}:5432
    build: {
      context: /db,
      dockerfile: dockerfile
    }
    restart: always
    networks:
      - net
    environment:
      - POSTGRES_DB=links
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data
  rmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=myname
      - RABBITMQ_DEFAULT_PASS=321
    networks:
      - net
    container_name: rmq
  server:
    image: server
    ports:
      - 3000:3000
    build: {
      context: /server,
      dockerfile: dockerfile
    }
    networks:
      - net
    depends_on:
      - db
      - rmq
    environment:
      - dbName=${POSTGRES_DB}
      - dbUser=${POSTGRES_USER}
      - dbPass=${POSTGRES_PASSWORD}
      - dbPort=${POSTGRES_PORT}
      - dbHost=db
    container_name: server
networks:
  net:
    driver: bridge
volumes:
  dbdata: